@startuml
'https://plantuml.com/state-diagram
[*] --> UpgradePhase
UpgradePhase -->PromgrammingPhase
PromgrammingPhase-->ActivationPhase
ActivationPhase-->UpgradePhase :WinnerNotFound
ActivationPhase-->GameOver: WinnerFound
GameOver-->[*]
@enduml